import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e6e0f0",
        tertiary: "#1b1924",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#1d1a26",
        "error-container": "#ffdad6",
        secondary: "#6b538c",
        outline: "#7b7481",
        "surface-tint": "#6e4da1",
        "on-secondary-fixed": "#260d45",
        "surface-variant": "#e7e0e8",
        "on-error-container": "#93000a",
        "on-background": "#1d1a20",
        "surface-container-low": "#f9f1f9",
        background: "#fef7ff",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#eddcff",
        "primary-fixed": "#ecdcff",
        "on-tertiary-container": "#9a94a4",
        "inverse-primary": "#d6baff",
        "on-primary-container": "#a986df",
        "on-primary": "#ffffff",
        "primary-container": "#3d1a6e",
        "on-tertiary-fixed-variant": "#484552",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#d7bafc",
        primary: "#260054",
        "on-surface-variant": "#4a4550",
        "secondary-container": "#dabdfe",
        "surface-dim": "#dfd8e0",
        "surface-bright": "#fef7ff",
        "on-primary-fixed-variant": "#563587",
        "outline-variant": "#ccc3d2",
        "tertiary-container": "#302d3a",
        "on-secondary-fixed-variant": "#533b73",
        error: "#ba1a1a",
        "primary-fixed-dim": "#d6baff",
        "on-surface": "#1d1a20",
        "inverse-surface": "#322f35",
        "surface-container": "#f3ecf4",
        "on-error": "#ffffff",
        "on-secondary-container": "#614982",
        "surface-container-highest": "#e7e0e8",
        "tertiary-fixed-dim": "#cac4d4",
        "surface-container-high": "#ede6ee",
        surface: "#fef7ff",
        "inverse-on-surface": "#f6eef7",
        "on-primary-fixed": "#280056",
      },
      fontFamily: {
        "body-md": ["Manrope"],
        "label-caps": ["Manrope"],
        "body-lg": ["Manrope"],
        "body-sm": ["Manrope"],
        h3: ["Epilogue"],
        h1: ["Epilogue"],
        h2: ["Epilogue"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        h3: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        h1: ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["36px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
      spacing: {
        margin: "32px",
        "container-max": "1280px",
        gutter: "24px",
        unit: "8px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
