'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { clearAuthSession } from '@/lib/auth-client';
const nav = [{ href:'/admin/painel', label:'Visão geral', icon:'space_dashboard' }, { href:'/admin/pesquisas', label:'Campanhas', icon:'campaign' }, { href:'/admin/pesquisas/inteligencia', label:'Criar Pesquisa', icon:'auto_awesome' }, { href:'/admin/relatorios', label:'Relatórios', icon:'bar_chart' }, { href:'/admin/acoes', label:'Plano de ação', icon:'task_alt' }, { href:'/admin/devolutivas', label:'Devolutivas', icon:'forum' }];
export function AdminSidebar() {
 const path=usePathname(); const [open,setOpen]=useState(false); const current=path;
 return <><button className="eq-mobile-menu" aria-label={open ? "Fechar navegação" : "Abrir navegação"} aria-expanded={open} aria-controls="company-navigation" onClick={()=>setOpen(!open)}><span aria-hidden="true" className="material-symbols-outlined">menu</span> Equilibra</button>{open && <button className="eq-scrim" aria-label="Fechar navegação" onClick={()=>setOpen(false)}/>}
 <aside id="company-navigation" className={'eq-sidebar '+(open?'is-open':'')}><Link href="/admin/painel" className="eq-brand"><span className="eq-brand-mark">e</span>equilibra<span className="eq-brand-dot">.</span></Link><p className="eq-nav-caption">ESPAÇO DA EMPRESA</p><nav aria-label="Navegação principal">{nav.map(n=>{const isActive=n.href==='/admin/pesquisas'?current==='/admin/pesquisas':current===n.href||current.startsWith(n.href+'/');return<Link aria-current={isActive?'page':undefined} key={n.href} href={n.href} onClick={()=>setOpen(false)} className={'eq-nav-item '+(isActive?'active':'')}><span aria-hidden="true" className="material-symbols-outlined">{n.icon}</span>{n.label}{isActive&&<span className="eq-active-dot"/>}</Link>;})}</nav><div className="eq-sidebar-bottom"><Link href="/admin/assinatura" className="eq-nav-item"><span aria-hidden="true" className="material-symbols-outlined">credit_card</span>Plano e assinatura</Link><button className="eq-nav-item" onClick={()=>{clearAuthSession();window.location.assign('/')}}><span aria-hidden="true" className="material-symbols-outlined">logout</span>Sair da conta</button></div></aside></>;
}
