'use client';
import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { authenticatedFetch } from '@/lib/api-client';
import { assessTrend } from '@/lib/product/trend';
import { PageReveal } from '@/components/admin/PageReveal';
import { ChartJsDashboard } from '@/components/admin/ChartJsDashboard';
type Plan = { title: string; steps: string[]; owner: string; days: number; evidence: string; indicator: string; resources: string };
type Finding = { id: string; name: string; text: string; count: number; percent: number; action: Plan };
type Report = { id: string; title: string; sector: string; openedAt: string; closedAt: string | null; released: boolean; completed: number; invited: number; minimum: number; findings: Finding[]; questions: { id: string; text: string; count: number | null; counts?: number[] | null; sentiment?: number[] | null }[]; note: string };
type Action = { id: string; batch_id: string; dimension_id: string; title: string; owner: string; due_date: string; status: string; evidence: string | null; plan: Plan };
type Dashboard = { company: string | null; reports: Report[]; actions: Action[] };
const box = 'eq-panel';
const field = 'eq-input';
const button = 'eq-primary';
const dates = (date: string) => new Date(date.length === 10 ? date + 'T12:00:00' : date).toLocaleDateString('pt-BR');
const statusName: Record<string, string> = { planned: 'Planejada', progress: 'Em andamento', done: 'Executada' };

export default function CompanyWorkspace({ view }: { view: 'overview' | 'results' | 'actions' | 'feedback' }) {
  const { user, loading } = useAuth('admin');
  const [data, setData] = useState<Dashboard | null>(null), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [tab, setTab] = useState(view === 'actions' ? 'Plano de ação' : view === 'feedback' ? 'Devolutiva' : 'Resultados'), [selected, setSelected] = useState(''), [busy, setBusy] = useState(false);
  const [draft, setDraft] = useState<Finding | null>(null), [owner, setOwner] = useState(''), [due, setDue] = useState(''), [title, setTitle] = useState('');
  const [editing, setEditing] = useState<Action | null>(null), [status, setStatus] = useState('planned'), [evidence, setEvidence] = useState('');
  const [reviewed, setReviewed] = useState(false);
  const load = useCallback(async () => {
    const r = await authenticatedFetch('/api/product/dashboard'); const d = await r.json();
    if (!r.ok) throw new Error(d.error || 'Não foi possível carregar o painel.');
    const requested = new URLSearchParams(window.location.search).get('run');
    setData(d); setSelected(s => s || (d.reports.some((r: Report) => r.id === requested) ? requested : '') || d.reports[0]?.id || '');
  }, []);
  useEffect(() => { if (user) load().catch(e => setError(e.message)); }, [user, load]);

  useEffect(() => {
    setReviewed(false); setDraft(null); setEditing(null);
    if (view !== 'actions') return;
    const findingId = new URLSearchParams(window.location.search).get('finding');
    const finding = data?.reports.find(r => r.id === selected)?.findings.find(f => f.id === findingId);
    if (finding) { setDraft(finding); setTitle(finding.action.title); setOwner(finding.action.owner); setDue(new Date(Date.now() + finding.action.days * 86400000).toISOString().slice(0,10)); }
  }, [selected, data, view]);
  async function mutate(method: string, body: unknown) {
    setBusy(true); setError(''); setNotice('');
    try { const r = await authenticatedFetch('/api/product/actions', { method, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); await load(); setDraft(null); setEditing(null); setNotice('Ação salva no histórico da empresa.'); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  const report = data?.reports.find(r => r.id === selected);
  const actions = data?.actions.filter(a => a.batch_id === selected) || [];
  const overdue = data?.actions.filter(a => a.status !== 'done' && a.due_date < new Date().toISOString().slice(0, 10)).length || 0;
  const feedback = report ? `${data?.company || 'Nossa empresa'} — Devolutiva\n${report.title} · ${report.sector}\nPeríodo: ${dates(report.openedAt)} a ${report.closedAt ? dates(report.closedAt) : 'em andamento'}\n\nO que ouvimos\n${report.findings.map(f => `${f.name}: ${f.percent}% das ${f.count} respostas válidas indicaram frequentemente ou sempre.`).join('\n') || 'Os dados por dimensão ainda não podem ser divulgados.'}\n\nMedidas registradas\n${actions.map(a => `${a.title} — ${statusName[a.status]}. Prazo: ${dates(a.due_date)}.`).join('\n') || 'A gestão ainda está avaliando as medidas. Nenhuma ação foi assumida neste painel.'}\n\nAcompanhamento\nA execução das medidas será acompanhada pela gestão. Os resultados representam percepções agregadas; uma nova avaliação será necessária para verificar mudanças.` : '';
  if (loading) return <main className="p-8">Verificando acesso…</main>;
  const pageTitle = { overview: 'Um olhar atento à sua empresa', results: 'Resultados que orientam decisões', actions: 'Da escuta à mudança', feedback: 'Feche o ciclo da escuta' }[view];
  const purpose = { overview: 'Veja o que precisa de atenção e decida seu próximo passo.', results: 'Entenda os achados e acompanhe a evolução entre campanhas.', actions: 'Defina responsáveis, acompanhe prazos e registre a execução.', feedback: 'Prepare uma comunicação clara sobre o que foi ouvido e será feito.' }[view];
  return (
    <main className="eq-page eq-dashboard space-y-6">
      <PageReveal selector=".eq-panel, .eq-overview-hero, .eq-metric, .eq-page-heading, .eq-recent-row" />
      <div className="eq-breadcrumb">ESPAÇO DA EMPRESA <span>/</span> {data?.company || 'EQUILIBRA'}</div>
    <header className="eq-page-heading"><div><span className="eq-eyebrow">{({overview:'VISÃO GERAL',results:'RESULTADOS',actions:'PLANO DE AÇÃO',feedback:'DEVOLUTIVAS'})[view]}</span><h1>{pageTitle}</h1><p>{purpose}</p></div></header>
    {error && <div role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}<button className="ml-4 underline" onClick={() => load().then(() => setError('')).catch(e => setError(e.message))}>Tentar novamente</button></div>}
    {notice && <p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{notice}</p>}
    {!data ? <p>Carregando indicadores…</p> : !data.reports.length ? <section className={box}><h2 className="text-xl font-semibold">Sua primeira escuta começa aqui</h2><p className="my-3 text-slate-600">Cadastre sua empresa e abra uma pesquisa para seus funcionários. Os indicadores aparecerão com as respostas reais; os resultados serão liberados após o encerramento e a proteção dos grupos pequenos.</p><Link href="/admin/pesquisas/inteligencia" className="font-semibold text-purple-800 underline">Preparar primeira pesquisa</Link></section> : <>
      {view === 'overview' && <>
        <section className="eq-overview-hero"><div><span className="eq-eyebrow">ESCUTAR. ENTENDER. TRANSFORMAR.</span><h2>Cuidar das pessoas<br/>começa com uma decisão.</h2><p>{overdue ? `${overdue} medida(s) com prazo vencido precisam de acompanhamento.` : data.reports.some(r => !r.closedAt) ? 'Sua escuta está em andamento. Acompanhe a participação antes de analisar os resultados.' : 'A coleta terminou. Examine os resultados para decidir onde agir primeiro.'}</p><Link className="eq-hero-button" href={overdue ? `/admin/acoes?run=${data.actions.find(a => a.status !== 'done' && a.due_date < new Date().toISOString().slice(0,10))?.batch_id}` : data.reports.some(r => !r.closedAt) ? '/admin/pesquisas/inteligencia' : '/admin/resultados'}>{overdue ? 'Acompanhar ações' : data.reports.some(r => !r.closedAt) ? 'Acompanhar coleta' : 'Analisar resultados'} <span aria-hidden="true">↗</span></Link></div><div className="eq-orbit-art" aria-hidden="true"><div/><div/><div/></div></section>
      <div className="eq-metrics">{[['Campanhas abertas', data.reports.filter(r => !r.closedAt).length, 'graphic_eq'], ['Coletas concluídas', data.reports.filter(r => r.closedAt).length, 'check_circle'], ['Ações em andamento', data.actions.filter(a => a.status !== 'done').length, 'task_alt'], ['Prazos vencidos', overdue, 'schedule']].map(([label, value, icon]) => <div key={label} className="eq-metric"><span className="material-symbols-outlined" aria-hidden="true">{icon}</span><p>{label}</p><strong>{value}</strong><small>{label === 'Prazos vencidos' ? 'Precisam de acompanhamento' : 'Nas últimas 30 campanhas'}</small></div>)}</div>
        <div className="eq-overview-grid"><section className="eq-panel"><div className="eq-section-title"><div><span className="eq-eyebrow">ACOMPANHAMENTO</span><h2>Campanhas recentes</h2></div><Link href="/admin/pesquisas/inteligencia">Ver todas ↗</Link></div><p className="eq-hint">As últimas coletas da sua empresa e o próximo destino de cada uma.</p><div className="eq-recent-list">{data.reports.slice(0,4).map(r => <Link className="eq-recent-row" key={r.id} href={r.closedAt ? `/admin/resultados?run=${r.id}` : '/admin/pesquisas/inteligencia'}><span className="eq-icon-tile"><span aria-hidden="true" className="material-symbols-outlined">{r.closedAt ? 'analytics' : 'graphic_eq'}</span></span><div><strong>{r.title}</strong><p>{r.sector} · {dates(r.openedAt)}</p></div><span className="eq-recent-status">{r.closedAt ? 'Ver resultados' : `${r.completed}/${r.invited} respostas`} →</span></Link>)}</div></section><section className="eq-panel eq-cycle"><span className="eq-eyebrow">COMO GERAR VALOR</span><h2>Um ciclo, quatro passos</h2>{[['01','Escute','Pesquisas','Prepare perguntas e acompanhe a coleta.'],['02','Entenda','Resultados','Analise os dados e a evolução.'],['03','Transforme','Plano de ação','Registre medidas, responsáveis e evidências.'],['04','Comunique','Devolutivas','Conte à equipe quais compromissos foram assumidos.']].map(([n,t,d,p])=><div className="eq-cycle-step" key={n}><span>{n}</span><div><strong>{t} <small>· {d}</small></strong><p>{p}</p></div></div>)}</section></div>
      </>}
      {view !== 'overview' && <>
      <div className="flex flex-wrap items-end gap-4"><label className="min-w-0 flex-1 text-sm font-medium">Rodada em análise<select className={field + ' mt-1'} value={selected} onChange={e => setSelected(e.target.value)}>{data.reports.map(r => <option value={r.id} key={r.id}>{r.title} · {r.sector} · {dates(r.openedAt)}</option>)}</select></label><p className="text-xs text-slate-500">Últimas 30 rodadas</p></div>
      {view === 'results' && <nav aria-label="Análises dos resultados" className="eq-analysis-tabs">{['Resultados', 'Evolução e previsões'].map(t => <button key={t} aria-current={tab === t ? 'page' : undefined} onClick={() => setTab(t)}>{t}</button>)}</nav>}
      {report && tab === 'Resultados' && <>
        <section className={box}><div className="flex justify-between gap-3"><h2 className="font-semibold">Participação na rodada</h2><span className="rounded-full bg-purple-50 px-3 py-1 text-xs text-purple-800">{report.closedAt ? 'Encerrada' : 'Em coleta'}</span></div><p className="my-3 text-2xl font-bold">{report.completed} <span className="text-base font-normal text-slate-500">respostas / {report.invited || Math.max(10, report.completed)} meta esperada</span></p><progress aria-label="Respostas em relação aos convites" value={report.completed} max={Math.max(1, report.invited || report.completed)} className="h-3 w-full accent-purple-800"/><p className="mt-2 text-xs text-slate-500">{report.invited ? Math.round(report.completed / report.invited * 100) : 100}% da meta atingida. Respostas 100% anônimas e protegidas.</p></section>

        {/* Dashboard com Chart.js: Gap Analysis, NR-1 Matriz de Risco e Evolução */}
        <div className="my-6">
          <ChartJsDashboard
            report={report}
            historicalRuns={data.reports.filter(r => r.sector === report.sector).map(r => ({ id: r.id, title: r.title, openedAt: r.openedAt, findings: r.findings }))}
          />
        </div>

        {!report.closedAt ? <section className={box}>Resultados preliminares gerados em tempo real. Os dados consolidados e laudos oficiais são liberados após o encerramento da rodada.</section> : !report.released ? <section className={box}>Resultado protegido: são necessárias pelo menos {report.minimum} participações para a emissão de laudo estatístico com sigilo.</section> : <section className={box}><h2 className="text-lg font-semibold">Condições que merecem atenção</h2><p className="mb-5 mt-1 text-sm text-slate-500">Frequência de respostas “Frequentemente” ou “Sempre” na base de condições de trabalho. Não representa probabilidade de adoecimento.</p>{report.findings.length ? <div className="space-y-5">{[...report.findings].sort((a,b) => b.percent - a.percent).map(f => <div key={f.id}><div className="flex justify-between text-sm"><span>{f.name}</span><strong>{f.percent}%</strong></div><div className="my-2 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-purple-600" style={{ width: `${f.percent}%` }}/></div><p className="text-xs text-slate-500">{f.count} respostas válidas · {f.text}</p><Link className="eq-finding-link" href={`/admin/acoes?run=${report.id}&finding=${f.id}`}>Avaliar medida sugerida <span aria-hidden="true">↗</span></Link></div>)}</div> : <p className="text-sm">Sem dimensões comparáveis liberadas. Perguntas personalizadas não recebem classificação automática; células pequenas permanecem protegidas.</p>}{report.questions.filter(q => q.count === null).length > 0 && <p className="mt-4 text-sm text-amber-800">Algumas perguntas estão ocultas para proteger grupos ou respostas pouco frequentes.</p>}</section>}
        {report.closedAt && report.released && <details className={box}><summary className="cursor-pointer font-semibold">Todas as perguntas e respostas agregadas <span className="ml-2 text-sm font-normal text-slate-500">{report.questions.length} perguntas</span></summary><div className="mt-5 space-y-5">{report.questions.map((q,i) => <article key={q.id} className="border-t pt-4"><h3 className="text-sm font-semibold">{i+1}. {q.text}</h3>{q.count===null?<p className="mt-2 text-sm text-slate-500">Resultado protegido para evitar identificar pessoas em grupos pequenos.</p>:q.counts?<div className="mt-3 grid gap-2">{q.counts.map((n,j)=><div className="flex items-center gap-3 text-xs" key={j}><span className="w-28 shrink-0">{['Nunca','Raramente','Às vezes','Frequentemente','Sempre'][j]}</span><div className="eq-meter flex-1"><span style={{width:`${q.count?n/q.count*100:0}%`}}/></div><span className="w-16 text-right">{n} respostas</span></div>)}</div>:<p className="mt-2 text-sm text-slate-500">{q.count} comentários classificados. Sinais preliminares: {q.sentiment?.map((n,j)=>`${['positivo','neutro','negativo','crítico'][j]}: ${n}`).join(' · ')}. A classificação por palavras-chave pode conter erros; os textos não são exibidos.</p>}</article>)}</div></details>}
      </>}
      {report && tab === 'Evolução e previsões' && <section className={box}><h2 className="text-lg font-semibold">Evolução observada e capacidade de previsão</h2><p className="mt-2 text-sm text-slate-600">Comparamos o mesmo setor e perguntas idênticas em rodadas encerradas. Mudanças na composição dos respondentes podem influenciar os resultados.</p>{!report.findings.length && <p className="mt-5">Ainda não há indicadores comparáveis liberados nesta rodada.</p>}{report.findings.map(f => {
        const comparable = data.reports.filter(r => r.sector === report.sector && r.closedAt && Date.parse(r.openedAt) <= Date.parse(report.openedAt) && r.questions.length === report.questions.length && r.questions.every((q,i) => q.id === report.questions[i].id && q.text === report.questions[i].text));
        const trend = assessTrend(comparable.flatMap(r => { const item = r.findings.find(x => x.id === f.id); return item ? [{ date: r.openedAt, value: item.percent }] : []; }));
        return <article key={f.id} className="mt-5 rounded-xl border p-4"><h3 className="font-semibold">{f.name}</h3><p className="my-2 text-sm">{trend.delta === null ? 'Primeira medição comparável.' : `Variação observada: ${trend.delta > 0 ? '+' : ''}${trend.delta} pontos percentuais em relação à rodada anterior.`}</p><div className="flex gap-3 overflow-x-auto py-3">{trend.points.map((p,i) => <div key={i} className="min-w-24 rounded-lg bg-purple-50 p-3 text-center"><strong className="text-purple-900">{p.value}%</strong><p className="mt-1 text-xs">{dates(p.date)}</p></div>)}</div>{trend.forecast && <div className="my-3 rounded-lg bg-amber-50 p-3 text-sm"><strong>Projeção experimental: {trend.forecast.value}%</strong><p>Próxima janela: {dates(trend.forecast.date)} · faixa histórica {trend.forecast.lower}–{trend.forecast.upper}%</p><p>Erro médio: {trend.forecast.mae} p.p.; referência: {trend.forecast.baselineMae} p.p.; {trend.forecast.tests} testes temporais.</p></div>}<p className="text-sm text-slate-500">{trend.reason}</p></article>;
      })}</section>}
      {report && tab === 'Plano de ação' && <div className="space-y-4"><section className={box}><h2 className="text-lg font-semibold">Medidas para esta rodada</h2><p className="mt-2 text-sm text-slate-500">Revise com SST e gestão. Executar uma medida não comprova sua eficácia; acompanhe o indicador em uma nova avaliação.</p><div className="mt-4 flex flex-wrap gap-2">{report.findings.map(f => <button key={f.id} className="rounded-lg border px-3 py-2 text-sm" onClick={() => { setDraft(f); setTitle(f.action.title); setOwner(f.action.owner); setDue(new Date(Date.now() + f.action.days * 86400000).toISOString().slice(0,10)); }}>{f.name}</button>)}</div>{!report.findings.length && <p className="mt-3 text-sm">As sugestões aparecerão com resultados liberados da base de condições de trabalho.</p>}</section>
        {draft && <form className={box + ' space-y-3'} onSubmit={e => { e.preventDefault(); mutate('POST', { runId: selected, dimensionId: draft.id, owner, dueDate: due, title }); }}><h3 className="font-semibold">Revisar proposta: {draft.name}</h3><p className="text-sm text-slate-600">Base: {draft.percent}% de {draft.count} respostas válidas. A causa precisa ser investigada pela equipe.</p><ol className="list-decimal space-y-1 pl-5 text-sm">{draft.action.steps.map(s => <li key={s}>{s}</li>)}</ol><p className="text-sm"><strong>Como verificar:</strong> {draft.action.indicator}</p><p className="text-sm"><strong>Recursos:</strong> {draft.action.resources}</p><label className="block text-sm">Medida aprovada<input required minLength={3} maxLength={255} className={field} value={title} onChange={e => setTitle(e.target.value)}/></label><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Responsável<input required minLength={2} maxLength={150} className={field} value={owner} onChange={e => setOwner(e.target.value)}/></label><label className="text-sm">Prazo<input required type="date" className={field} value={due} onChange={e => setDue(e.target.value)}/></label></div><button disabled={busy} className={button}>Registrar ação</button><button type="button" className="ml-4 text-sm" onClick={() => setDraft(null)}>Cancelar</button></form>}
        {!actions.length && <p className="text-sm text-slate-500">Nenhuma medida registrada nesta rodada.</p>}{actions.map(a => <article key={a.id} className={box}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{a.title}</h3><span className="text-sm text-purple-800">{statusName[a.status]}</span></div><p className="mt-2 text-sm">{a.owner} · prazo {dates(a.due_date)}{a.status !== 'done' && a.due_date < new Date().toISOString().slice(0,10) ? ' · Atrasada' : ''}</p><p className="mt-2 text-sm text-slate-500">Verificação: {a.plan.indicator}</p>{a.evidence && <p className="mt-2 whitespace-pre-wrap text-sm">Evidência registrada: {a.evidence}</p>}<button className="mt-3 text-sm font-semibold text-purple-800 underline" onClick={() => { setEditing(a); setStatus(a.status); setEvidence(a.evidence || ''); }}>Atualizar execução</button>{editing?.id === a.id && <form className="mt-4 space-y-3" onSubmit={e => { e.preventDefault(); mutate('PATCH', { id: a.id, status, evidence }); }}><label className="block text-sm">Estado<select className={field} value={status} onChange={e => setStatus(e.target.value)}>{Object.entries(statusName).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label><label className="block text-sm">Evidência e observações<textarea required={status === 'done'} minLength={status === 'done' ? 10 : undefined} maxLength={2000} className={field} value={evidence} onChange={e => setEvidence(e.target.value)} placeholder="Registre a mudança realizada, sem dados pessoais dos respondentes."/></label><button disabled={busy} className={button}>Salvar atualização</button></form>}</article>)}</div>}
      {report && tab === 'Devolutiva' && <section className={box}><h2 className="text-lg font-semibold">O que devolver aos funcionários</h2><p className="mt-2 text-sm text-slate-600">Revise o resumo e os compromissos antes de compartilhar pelos canais internos. Nomes dos responsáveis e textos de evidência não entram neste resumo.</p>{!report.closedAt || !report.released || !report.findings.length ? <p className="mt-5 text-amber-800">A devolutiva exige rodada encerrada e indicadores agregados liberados.</p> : <><article id="product-report" className="my-5 whitespace-pre-wrap rounded-xl bg-slate-50 p-5 text-sm leading-7">{feedback}</article><label className="flex gap-2 text-sm"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)}/>Revisei o conteúdo e os compromissos para compartilhar com os funcionários.</label><div className="mt-4 flex gap-3"><button disabled={!reviewed} className={button} onClick={async () => { try { await navigator.clipboard.writeText(feedback); setNotice('Devolutiva copiada. Compartilhe pelo canal interno da empresa.'); } catch { setError('Não foi possível copiar. Selecione o texto da devolutiva.'); } }}>Copiar devolutiva</button><button disabled={!reviewed} className={button} onClick={() => window.print()}>Salvar em PDF / imprimir</button></div></>}</section>}
      </>}
    </>}
    </main>
  );
}
